[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libPy"
version = "1.0"
description = "util lib for python projects"
requires-python = ">=3.8"
