[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libPy"
version = "1.0"
description = "util lib for python projects"
requires-python = ">=3.8"
dependencies = [
    "colorlog>=6.10.1",
    "discord>=2.3.2",
    "discord-py>=2.6.4",
]
